### PR TITLE
Projects

### PR DESCRIPTION
**Pull request by rjenc29**
initial thoughts on ols exensions

### CODE REVIEW

**Comment by dwillmer** [comment]
Awesome :)

**Comment by dwillmer** [comment]
SSR, SST and r_squared look awesome!

that's exactly what we want! :)

**Comment by rjenc29** [comment]
added adjusted r squared, for laughs

**Comment by dwillmer** [comment]
looks good to me!

**Comment by dwillmer** [comment]
i like the use of statsmodels for unit-testing!

**Comment by dwillmer** [comment]
Looks awesome - you want to merge and iterate on the main repo?

**Pull request closed without merging**
